### PR TITLE
added rainews.it. fix #127

### LINKED ISSUE #127: Add Italian news
It is finally possible to have news from RaiNews, from Italy. It would be nice to implement them.

Todo: support multiple radio

### PR DESCRIPTION
**Pull request by denics**
Fixes #127

This pull request add the italian GR1 to the list of radios. 

TODO add variable to manage all other rainews radio

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey, thanks for this.

The one thing that we've been avoiding is changing the settingsmeta.

The short story is that any change to it will cause all existing users to effectively have their settings wiped. Neither scenario is ideal:
1. People can't select this station from their Skill settings; Or
2. Everyone who has configured a custom default station will have it reset when the Skill updates.

It's something that we are addressing on the backend but until it's fixed we've decided to leave the settings definition as is. 

On the plus side, any users with their device location set to Italy will get this station as their new default :tada:

**Comment by denics** [comment]
Do you want me then to remove the changes in settingsmeta? Anyway, this would be so easily avoided if we allow a [user] configuration for skills too like suggested [here](https://github.com/MycroftAI/mycroft-core/pull/2519)

**Comment by denics** [comment]
Hi @krisgesling I have removed my changes from settingsmeta and I have added the radio image. Thanks

**Review by krisgesling — APPROVED** [review]
Great thanks!

Seems to be working well - I have no idea what it said but lots of Italian sounding news :smile:

**Pull request merged**
