### PR TITLE
Improving RSS handling

### PR DESCRIPTION
**Pull request by westfalenyeti**
Based on the work of @juhi24 and the refactoring of @forslund I lifted the code to the actual 18.08 release.
Please merge this PR as it seems that several people do have the problem, that the first RSS feed entry is not the audio file.

P.S. This is my 1st PR ever, so please advise if i could improve anything.

### CODE REVIEW

**Comment by KathyReid** [comment]
Thanks so much for your PR, @westfalenyeti :-) 
To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Thanks @westfalenyeti, I'd completely forgotten this. as soon as the CLA is completed I'll look at merging it!

**Comment by juhi24** [comment]
I hope this gets merged finally. My PR back in April was a simple fix to a simple problem that seems to be affecting a lot of users, and didn't have code conflicts. While I understand unexpected delays can happen in a project the size of Mycroft, this might be an indication that there is room for streamlining.

Congrats on your first PR, @westfalenyeti !

**Comment by juhi24** [comment]
Oho, missed @forslund 's comment until just now. Kind of guessed that's what happened, no worries :)

**Comment by forslund** [comment]
Sorry @juhi24 I'm terrible :)

**Comment by westfalenyeti** [comment]
@KathyReid @forslund Hi, just in case : CLA signed and submitted on Nov. 9th as requested. (Additionally to my anouncement on the mattermost channel  #skills )

**Comment by forslund** [comment]
Finally got around to testing this. Seems to work really nice. Thanks!

**Comment by juhi24** [comment]
Thank you Åke! I now have a good reason to switch back to official builds :)

**Comment by forslund** [comment]
@juhi24 thanks for being patient. Hopefully your next contribution will be smoother.

**Pull request merged**
